name = "c"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "c_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "c.wasm"
command = "npm run build:release"
